- name: Install gluster server
  ansible.builtin.apt:
    pkg: gluster-server
    state: present

- name: Ensure gluster is Started and enabled
  ansible.builtin.systemd_service:
    name: glusterd
    state: started
    enabled: true

- name: Probe peers
  gluster.gluster.gluster_peer:
    state: present
    nodes:
      - "{{ gluster_peers }}"


- name: Create directory
  ansible.builtin.file:
    dest: /gluster/brick1
    mode: '0750'
    owner: root
    group: root
    state: directory

- name: Create gluster volume
  gluster.gluster.gluster_volume:
    state: present
    name: swag
    bricks: /gluster/brick1/swag
    cluster:
      - "{{ gluster_peers }}"
  run_once: true

- name: Start gluster volume
  gluster.gluster.gluster_volume:
    state: started
    name: swag

- name: Mount gluster volume
  ansible.posix.mount:
    src: "localhost:swag"
    path: /home/pi/nfsdocker-volume/swag
    opts: defaults,_netdev
    state: mounted
    fstype: glusterfs

- name: Test Mount
  ansible.builtin.copy:
    src: files/test.txt
    dest: /home/pi/nfsdocker-volume/swag
    owner: pi
    group: pi
    mode: '0644'
  when: "'pi5' in inventory_hostname"

- name: Check file exists on node2
  ansible.builtin.stat:
    path: '/home/pi/nfsdocker-volume/swag/test.txt'
  register: file_exists

- name: Show debug
  ansible.builtin.debug:
    msg: "File exists"
  when: file_exists.stat.exists

# Alt method
- name: Read File on other node
  ansible.builtin.debug:
    msg: "{{ lookup('ansible.builtin.file', '/home/pi/nfsdocker-volume/swag/test.txt') }}"
  register: filetest

- name: Check file
  ansible.builtin.debug:
    var: filetest

- name: Cleanup test file
  ansible.builtin.file:
    dest: '/home/pi/nfsdocker-volume/swag/test.txt'
    state: absent
