- name: Create Pi-Hole Docker dir
  ansible.builtin.file:
    state: directory
    path: "{{ pi_hole_dir }}"
    mode: "0755"
    owner: "{{ user }}"
    group: admins

- name: Template compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ pi_hole_dir }}/docker-compose.yml"
    mode: "0664"
    owner: root
    group: admins

- name: Start container
  community.docker.docker_compose_v2:
    project_src: "{{ pi_hole_dir }}"
    state: present
    pull: always
    remove_orphans: true
