
- name: "Update Apt Cache"
  apt: 
    update_cache: yes
  tags: installation

- name: "Install Common packages"
  apt:
    pkg:
    - python3-pip
    - python3-venv
    - git
    - libffi-dev
    - libssl-dev
    - python3
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - dnsutils
    - screen
    - docker
    state: latest
  tags: installation, packages

- name : Remove packages
  apt:
    pkg: 
      - python-configparser
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent 
    autoclean: yes
