---
# Run with ansible-playbook base.yml
- name: Setup Base
  hosts: all
  remote_user: "{{ user }}"
  become: true
  become_method: sudo
  gather_facts: true

  pre_tasks:
    - name: Update Apt Cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Update packages
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: true
        force_apt_get: true
  roles:
    - users
    - packages
    # - server
