---
# Run with ansible-playbook -i inventory/hosts crowdsec.yml
- name: Setup crowdsec
  hosts: crowdsec
  remote_user: "{{ user }}"
  become: true
  become_method: sudo
  gather_facts: true

  roles:
    - users
    - docker
    - crowdsec
    - update_consul
