---
# Run with ansible-playbook docker-host.yml
- name: Setup Docker host
  hosts: docker_servers
  remote_user: "{{ user }}"
  become: true
  become_method: sudo
  gather_facts: true

  roles:
    - users
    - packages
    - docker
