---
# Run with ansible-playbook -i inventory/hosts gitlab-server.yml
- name: Setup gitlab server
  hosts: gitlab_server
  remote_user: "{{ user }}"
  become: true
  become_method: sudo
  gather_facts: true

  pre_tasks:
    - name: Update Apt Cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
  roles:
    - users
    - docker
    - gitlab_server
