---
# Run with ansible-playbook -i inventory/hosts grafana_server.yml
- name: Setup grafana server
  hosts: grafana_servers
  remote_user: "{{ user }}"
  become: true
  become_method: sudo
  gather_facts: true
  vars:
    service: grafana
  pre_tasks:
    - name: Update Apt Cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
  roles:
    - users
    - docker
    - grafana_server
