---
# Run with ansible-playbook -i inventory/hosts immich.yml
- name: Setup Immich
  hosts: immich
  remote_user: "{{ user }}"
  become: true
  become_method: sudo
  gather_facts: true

  roles:
    - users
    - docker
    - immich
    - update_consul
