---
# Run with ansible-playbook -i inventory/hosts lancache.yml
- name: Setup Lancache
  hosts: lancache
  remote_user: "{{ user }}"
  become: true
  become_method: sudo
  gather_facts: true


  roles:
    - users
    - docker
    - lancache
