---
# Run with ansible-playbook -i inventory/hosts mimir_server.yml
- name: Setup mimir server
  hosts: mimir_servers
  remote_user: "{{ user }}"
  become: true
  become_method: sudo
  gather_facts: true

  pre_tasks:
    - name: Update Apt Cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
  roles:
    - users
    - docker
    - mimir_server
