---
# Run with ansible-playbook -i inventory/hosts pi-hole.yml
- name: Setup Pi-Hole
  hosts: pi_hole
  remote_user: "{{ user }}"
  become: true
  become_method: sudo
  gather_facts: true

  roles:
    - users
    - docker
    - pi_hole
