---
# Setup Fresh RPi as a docker host

# Update system

- name: Update
  hosts: localhost
  become: true
  become_user: root
  tasks:
    - name: Update apt repo and cache on all Pi's
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  
    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes

# Install base software

    - name: Install Base software
      apt:
        name: 
            - git 
            - libffi-dev
            - libssl-dev
            - python3
            - python3-pip
        state: present
    - name : Remove packages
        name: 
            - python-configparser
        state: absent 

# Change default password

    - name : Change default password 
        user: pi
        password:

# Install docker and docker-compose

# Create docker and docker-volumes directory

# Pull docker compose from Git

# Create SSH Key 

    - name: Create a 2048-bit SSH key for user pi in ~pi/.ssh/pi_rsa
        user:
         name: pi
         generate_ssh_key: yes
         ssh_key_bits: 2048
         ssh_key_file: .ssh/pi_rsa

