---
- name: Update Conul KV
  hosts: all
  become: true
  tasks:
    - name: Add traefik label to Consul for GitLab
      community.general.consul_kv:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
        host: consul.0lzi.com
        port: 443
        scheme: "https"
        state: present
      loop: "{{ lookup('vars', service).traefik_labels | dict2items }}"
      delegate_to: localhost
      tags: consul
