---
# Run with ansible-playbook -i inventory/hosts uptime-kuma.yml
- name: Setup Diun
  hosts: docker_hosts
  remote_user: "{{ user }}"
  become: true
  become_method: sudo
  gather_facts: true

  pre_tasks:
    - name: Update Apt Cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
  roles:
    - users
    - docker
    - uptime-kuma
