---
# Run with ansible-playbook -i inventory/hosts uptime-kuma.yml
- name: Setup Diun
  hosts: docker_servers
  remote_user: "{{ user }}"
  become: true
  become_method: sudo
  gather_facts: true

  roles:
    - users
    - docker
    - uptime_kuma
    - update_consul
