---
# Run with ansible-playbook -i inventory/hosts main.yml
- name: Setup Docker pi
  hosts: pi
  remote_user: pi
  become: true
  become_method: sudo
  gather_facts: true
  vars_files:
    - ./vars/vars.yml

  pre_tasks:
    - name: Update Apt Cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
  roles:
    - docker

- name: Setup nfs-server
  hosts: nfs-server
  remote_user: pi
  become: true
  become_method: sudo
  gather_facts: true
  vars_files:
    - ./vars/vars.yml

- name: Setup nfs-clients
  hosts: pi , !nfs-server
  become: true
  become_method: sudo
  gather_facts: true
  vars_files:
    - ./vars/vars.yml
  roles:
    - nfs-client
