---
- name: Systemd-resolved
  ansible.builtin.systemd_service:
    state: restarted
    enabled: true
    name: systemd-resolved

- name: Systemd-daemon
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Steam-timer
  ansible.builtin.systemd_service:
    name: steamprefill.timer
    enabled: true
    state: started

- name: Steam-service
  ansible.builtin.systemd_service:
    name: steamprefill.service
    state: stopped
    enabled: true

- name: Epic-timer
  ansible.builtin.systemd_service:
    name: epicprefill.timer
    enabled: false
    state: stopped

- name: Epic-service
  ansible.builtin.systemd_service:
    name: epicprefill.service
    state: stopped
    enabled: false

- name: Battlenet-timer
  ansible.builtin.systemd_service:
    name: battlenetprefill.timer
    enabled: false
    state: stopped

- name: Battlenet-service
  ansible.builtin.systemd_service:
    name: battlenetprefill.service
    state: stopped
    enabled: false
