---
- name: Systemd-resolved
  ansible.builtin.systemd_service:
    state: restarted
    enabled: true
    name: systemd-resolved

- name: Systemd-daemon
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Steam-timer
  ansible.builtin.systemd_service:
    name: steamprefill.timer
    enabled: "{{ steamprefill | ternary('true', 'false') }}"
    state: "{{ steamprefill | ternary('started', 'stopped') }}"

- name: Steam-service
  ansible.builtin.systemd_service:
    name: steamprefill.service
    enabled: "{{ steamprefill | ternary('true', 'false') }}"
    state: "{{ steamprefill | ternary('started', 'stopped') }}"

- name: Epic-timer
  ansible.builtin.systemd_service:
    name: epicprefill.timer
    enabled: "{{ epicprefill | ternary('true', 'false') }}"
    state: "{{ epicprefill | ternary('started', 'stopped') }}"

- name: Epic-service
  ansible.builtin.systemd_service:
    name: epicprefill.service
    enabled: "{{ epicprefill | ternary('true', 'false') }}"
    state: "{{ epicprefill | ternary('started', 'stopped') }}"

- name: Battlenet-timer
  ansible.builtin.systemd_service:
    name: battlenetprefill.timer
    enabled: "{{ battlenetprefill | ternary('true', 'false') }}"
    state: "{{ battlenetprefill | ternary('started', 'stopped') }}"

- name: Battlenet-service
  ansible.builtin.systemd_service:
    name: battlenetprefill.service
    state: "{{ battlenetprefill | ternary('started', 'stopped') }}"
    enabled: "{{ battlenetprefill | ternary('true', 'false') }}"
