---

- name: Create immich user
  ansible.builtin.user:
    name: immich
    state: present
    system: true

- name: Create data directory
  ansible.builtin.file:
    path: "{{ immich_data }}"
    state: directory
    mode: '0755'
    owner: immich
    group: admins

- name: Fetch latest compsose file
  ansible.builtin.get_url:
    url: "{{ immich_compose_url }}"
    dest: "{{ immich_data }}"
    mode: '0644'
    owner: immich
    group: admins
  notify:
    - Restart_container
    - Pull images

- name: Template .env file
  ansible.builtin.template:
    src: env.j2
    dest: "{{ immich_data }}/.env"
    mode: '0644'
    owner: immich
    group: admins
  notify: Restart_container

- name: Template config file
  ansible.builtin.template:
    src: immich-config.json.j2
    dest: "{{ immich_data }}/immich-config.json"
    mode: '0644'
    owner: immich
    group: admins
  notify: Restart_container

- name: Start container
  community.docker.docker_compose_v2:
    project_src: "{{ immich_data }}"
    state: present
