---
openbao_url: "https://vault.0lzi.com"
openbao_download_url: "https://github.com/openbao/openbao/releases/download/v{{ openbao_version }}/openbao_{{ openbao_version }}_linux_amd64.deb"
openbao_version: "2.5.4"
openbao_agent_config_dir: "/etc/openbao.d"
openbao_agent_data_dir: "/opt/openbao/data"
openbao_agent_cert_dir: "{{ openbao_agent_config_dir }}/certs"
openbao_agent_log_dir: "/var/log/openbao-agent"
openbao_agent_approle_name: "approle-auth"
# openbao_agent_approle_name: "agent-approle-auth"
