- name: Systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart_openbao
  ansible.builtin.systemd:
    service: openbao
    state: restarted

- name: Unseal vault # noqa no-changed-when command-instead-of-shell run-once[task]
  ansible.builtin.shell: /usr/bin/bao operator unseal {{ item }}
  environment:
    BAO_SKIP_VERIFY: "1"
    BAO_ADDR: "{{ tls.enabled | ternary('https', 'http') }}://127.0.0.1:8200"
  loop: "{{ unseal_keys[0:3] }}"

- name: Enable_service
  ansible.builtin.systemd:
    service: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - openbao-backup.timer
    - openbao-backup.service
