---
- name: Set up BattleNetPrefill
  ansible.builtin.file:
    path: /srv/BattleNetPrefill
    state: directory
    mode: '0755'
    owner: root
    group: admins

- name: Download BattleNetPrefill updater
  ansible.builtin.get_url:
    url: "{{ lancache_battlenetprefill_url }}"
    dest: /srv/BattleNetPrefill/update.sh
    mode: '0755'

- name: Run update.sh
  ansible.builtin.shell:
    cmd: set -o pipefail && ./update.sh
    executable: /bin/bash
    chdir: /srv/BattleNetPrefill
  register: update_script
  changed_when: false

- name: Create systemd timer for BattleNetPrefill
  ansible.builtin.template:
    src: battlenetprefill.timer
    dest: /etc/systemd/system/battlenetprefill.timer
    mode: '0644'
  changed_when: true
  notify:
    - Systemd-daemon
    - Battlenet-timer

- name: Create systemd timer for BattleNetPrefill
  ansible.builtin.template:
    src: battlenetprefill.service
    dest: /etc/systemd/system/battlenetprefill.service
    mode: '0644'
  changed_when: true
  notify:
    - Systemd-daemon
    - Battlenet-service
