---
- name: Install prequisite packages
  ansible.builtin.apt:
    name: "{{ lancache_pkgs }}"
    state: present

- name: Setup SteamPrefill
  ansible.builtin.include_tasks: steamprefill.yml
  when: steamprefill == true

- name: Setup EpicPrefill
  ansible.builtin.include_tasks: epicprefill.yml
  when: epicprefill == true

- name: Setup BattleNetPrefill
  ansible.builtin.include_tasks: battlenetprefill.yml
  when: battlenetprefill == true

- name: Setup Lancache
  ansible.builtin.include_tasks: lancache.yml
