---
- name: Install prequisite packages
  ansible.builtin.apt:
    name: "{{ lancache_pkgs }}"
    state: present

- name: Setup SteamPrefill
  ansible.builtin.include_tasks: steamprefill.yml

- name: Setup EpicPrefill
  ansible.builtin.include_tasks: epicprefill.yml

- name: Setup Lancache
  ansible.builtin.include_tasks: lancache.yml
