quotas:
  - project: 'admin'
    project_domain: 'Default'
    user_domain: 'Default'
    floating_ips: -1
    networks: -1
    ports: -1
    rbac_policies: -1
    routers: -1
    subnets: -1
    subnet_pools: -1
    security_group_rules: -1
    security_groups: -1
    backup_gigabytes: -1
    backups: -1
    gigabytes: -1
    groups: -1
    pools: -1
    per_volume_gigabytes: -1
    snapshots: -1
    volumes: -1
    cores: -1
    instances: -1
    key_pairs: -1
    metadata_items: -1
    ram: -1
    server_groups: -1
    server_group_members: -1
  - project: 'demo'
    project_domain: 'home'
    user_domain: 'home'
    floating_ips: 1
    networks: 1
    ports: 1
    rbac_policies: 1
    routers: 1
    subnets: 1
    subnet_pools: 1
    security_group_rules: 10
    security_groups: 1
    backup_gigabytes: 100
    backups: 5
    gigabytes: 30
    groups: 1
    pools: 1
    per_volume_gigabytes: 30
    snapshots: 2
    volumes: 3
    cores: 6
    instances: 20
    key_pairs: 30
    metadata_items: 10
    ram: 65536
    server_groups: 2
    server_group_members: 10
