- name: Copy aliases
  ansible.builtin.copy:
    src: .bash_aliases
    dest: /home/pi/.bash_aliases
    owner: pi
    group: pi
    mode: '0644'
  tags: aliases

- name: Update Bashrc
  ansible.builtin.blockinfile:
    dest: /home/pi/.bashrc
    block: |
     if [ -f ~/.bash_aliases ]; then
     . ~/.bash_aliases
     fi
    backup: true


- name: Update Apt Cache
  ansible.builtin.apt:
    update_cache: true
