- name: Copy aliases
  ansible.builtin.copy:
    src: ./files/custom.aliases.sh
    dest: /home/pi/.oh-my-bash/custom/aliases
    owner: pi
    group: pi
    mode: '0644'
  tags: aliases

- name: Copy SSH Config
  ansible.builtin.copy:
    src: .ssh_config
    dest: /home/pi/.ssh/config
    owner: pi
    group: pi
    mode: '0644'
  tags: config
  
- name: Set oh-my-bash theme
  ansible.builtin.lineinfile:
    path: /home/pi/.bashrc
    search_string: 'OSH_THEME='
    line: OSH_THEME="rr"


