- name: Add a line to /etc/fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "#{{ nfs_server }}:/media/usb-storage/docker  /home/pi/nfsdocker    nfs     defaults        0       0"
    create: true

- name: Add a line to /etc/fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "#{{ nfs_server }}:/media/usb-storage/docker-volumes  /home/pi/nfsdocker-volumes    nfs     defaults        0       0"
    create: true

- name: Add a line to /etc/fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "{{ uuid }}  /media/usb-storage/     ext4 defaults   0       0"
    create: true

- name: Mount nfs
  ansible.builtin.command: mount -a

- name: Create nfsdocker DIR
  ansible.builtin.file:
    src: "/media/usb-storage/docker"
    dest: "/home/pi/nfsdocker"
    state: link
    owner: pi
    group: pi

- name: Create nfsdocker-volumes DIR
  ansible.builtin.file:
    src: "/media/usb-storage/docker-volumes"
    dest: "/home/pi/nfsdocker-volumes"
    state: link
    owner: pi
    group: pi