- name: Install Applications
  apt:
    pkg:
    - python3-pip
    - python3-venv
    - git
    - libffi-dev
    - libssl-dev
    - python3
    - apt-transport-https
    - gnupg-agent
    - software-properties-common
    - dnsutils
    - screen
    - htop
    - docker-ce 
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
    - nfs-common
    - nfs-kernel-server
    - fonts-powerline
    state: latest
  tags: installation, packages

- name: Install oh-my-bash 
  ansible.builtin.shell: bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh) --unattended"
  become: false
  ignore_errors: true