---
- name: Restart Containers
  hosts: all
  become: true
  gather_facts: true
#  vars_files:
#    ./vars/vars.yml

  tasks:
    - name: Get containers
      community.docker.docker_host_info:
        containers: true
      register: pre_restart

    - name: Show Number of containers
      ansible.builtin.debug:
        msg: "Hostname - {{ pre_restart.host_info.Name }} has {{ pre_restart.host_info.Containers }} Containers "

    - name: Restart containers
      ansible.builtin.shell: "docker restart $(docker ps -a -q)"