---
- name: Authenticate to Openstack
  hosts: localhost
  gather_facts: false
  vars_files:
    - auth.yml

  tasks:
    - name: Authenticate to cloud and return auth token
      openstack.cloud.auth:
        cloud:
          auth:
            auth_url: "{{ auth_url }}"
            username: "{{ username }}"
            password: "{{ password }}"
            project_name: "{{ project_name }}"
            project_domain_name: Default
            user_domain_name: Default
          region_name: "{{ region_name }}"
      register: os_auth

    - name: debug
      debug:
        var: os_auth.ansible_facts.auth_token
 
