---
- name: Restart Containers
  hosts: all
  become: true
  gather_facts: true
#  vars_files:
#    ./vars/vars.yml

  tasks:
    - name: Get running containers
      community.docker.docker_host_info:
        containers: true
      register: pre_restart

    - name: Show Number of containers running
      ansible.builtin.debug:
        msg: "Hostname - {{ pre_restart.host_info.Name }} has {{ pre_restart.host_info.ContainersRunning }} Containers "

    - name: Restart containers
      community.docker.docker_container:
        name: "{{ item }}"
        state: started
        restart: true
      loop: "{{ pre_restart.containers | map(attribute='Id') | list }}"

    - name: Get running containers
      community.docker.docker_host_info:
        containers: true
      register: post_restart

    - name: Compare Pre - Post Containers
      ansible.builtin.debug:
        msg: "Pre-reboot Containers {{ pre_restart.host_info.ContainersRunning }} - Post-reboot Containers {{ post_restart.host_info.ContainersRunning }}"
      failed_when: pre_restart.host_info.ContainersRunning != post_restart.host_info.ContainersRunning
