- name: Create nfsdocker DIR
  ansible.builtin.file:
    path: "/home/pi/nfsdocker"
    state: directory
    mode: '755'
    owner: pi
    group: pi

# - name: Create nfsdocker-volumes DIR
#   ansible.builtin.file:
#     path: "/home/pi/nfsdocker-volumes"
#     state: directory
#     mode: '755'
#     owner: pi
#     group: pi

- name: Stop service nfs-kernel-server, if started
  ansible.builtin.service:
    name: nfs-kernel-server
    state: stopped
    enabled: false

- name: Mount an NFS volume
  ansible.posix.mount:
    src: "{{ nfs_server }}:/media/usb-storage/docker"
    path: /home/pi/nfsdocker
    opts: rw,sync,hard
    state: mounted
    fstype: nfs

# - name: Mount an NFS volume
#   ansible.posix.mount:
#     src: "{{ nfs_server }}:/media/usb-storage/docker-volumes"
#     path: /home/pi/nfsdocker-volumes
#     opts: rw,sync,hard
#     state: mounted
#     fstype: nfs

- name: Mount up device by UUID
  ansible.posix.mount:
    path: /media/usb-storage
    src: "{{ uuid }}"
    fstype: ext4
    opts: defaults,noatime
    state: absent

# - name: Add a line to /etc/fstab
#   ansible.builtin.lineinfile:
#     path: /etc/fstab
#     line: "{{ nfs_server }}:/media/usb-storage/docker  /home/pi/nfsdocker    nfs     defaults        0       0"
#     create: true

# - name: Add a line to /etc/fstab
#   ansible.builtin.lineinfile:
#     path: /etc/fstab
#     line: "{{ nfs_server }}:/media/usb-storage/docker-volumes  /home/pi/nfsdocker-volumes    nfs     defaults        0       0"
#     create: true

# - name: Add a line to /etc/fstab
#   ansible.builtin.lineinfile:
#     path: /etc/fstab
#     line: "#{{ uuid }}  /media/usb-storage/     ext4 defaults   0       0"
#     create: true

# - name: Mount nfs
#   ansible.builtin.command: mount -a
