---
- hosts: all
  become: yes
  tasks:
    - name: Update apt cache and make sure apps are installed & updated
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
          - python3-pip
          - python3-venv
          - git
          - libffi-dev
          - libssl-dev
          - python3
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - dnsutils
          - docker
          - screen


