---
- name: Demo Ruleset for Webhook
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Run playbook
      condition: event.payload.message == "update pi"
      action:
        run_playbook:
          name: Demo Playbook Template
          organization: Default
          inventory: Pi