- name: Copy aliases
  ansible.builtin.copy:
    src: ./files/custom.aliases.sh
    dest: /home/pi/.oh-my-bash/custom/aliases
    owner: pi
    group: pi
    mode: '0644'
  tags: aliases

- name: Check .ssh path
  ansible.builtin.file:
    dest: /home/pi/.ssh
    owner: pi
    group: pi
    mode: '0700'
    state: directory
  tags: config

- name: Copy SSH Config
  ansible.builtin.copy:
    src: .ssh_config
    dest: /home/pi/.ssh/config
    owner: pi
    group: pi
    mode: '0644'
  tags: config

- name: Set oh-my-bash theme
  ansible.builtin.lineinfile:
    path: /home/pi/.bashrc
    search_string: 'OSH_THEME='
    line: OSH_THEME="rr"

- name: Copy Exports
  ansible.builtin.template:
    src: templates/exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'

# - name: Add custom aliases
#   ansible.builtin.blockinfile:
#     path: /home/pi/.bashrc
#     insertafter: 'aliases=('
#     block: |
#       general
#       custom
#       )

# - name: Set authorized keys from file
#    ansible.posix.authorized_key:
#      user: pi
#      state: present
#      key: "{{ lookup('file','ansible/pi-test/files/laptop.pub') }}"

# - name: Set boot Options
#   ansible.builtin.lineinfile:
#     path: /boot/cmdline.txt
#     search_string: 'rootwait'
#     line: 'rootwait fsck.mode=force'


# - name: Disable onboard wifi
#   ansible.builtin.blockinfile:
#     path: /boot/config.txt
#     insertafter: '[all]'
#     marker: "<!-- {mark} Ansible Managed Block -->"
#     block: |
#       gpu_mem=16
#       dtoverlay=disable-wifi
#       dtoverlay=disable-bt
