- name: Set the current MAC address for eth0.
  ansible.builtin.set_fact:
    pi_mac_address: "{{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress }}"

- name: Set variables based on eth0 MAC address.
  ansible.builtin.set_fact:
    pi_hostname: "{{ mac_address_mapping[pi_mac_address].name }}"
    pi_ip_address: "{{ mac_address_mapping[pi_mac_address].ip }}"

# For Debian 11 Raspbery PiOs
- name: Set up networking-related files.
  ansible.builtin.template:
    src: "templates/{{ item.template }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  with_items:
    - { template: hostname.j2, dest: /etc/hostname }
    - { template: resolv.conf.j2, dest: /etc/resolv.conf }
    - { template: dhcpcd.conf.j2, dest: /etc/dhcpcd.conf }
  notify:
    - update hostname
  when: ansible_distribution_major_version == "11"

# For Debian 12 Raspbery PiOs
- name: Set up networking-related files.
  ansible.builtin.template:
    src: "templates/{{ item.template }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  with_items:
    - { template: hostname.j2, dest: /etc/hostname }
    - { template: resolv.conf.j2, dest: /etc/resolv.conf }
    - { template: interface.j2, dest: /etc/network/interfaces }
  notify:
    - update hostname
  when: ansible_distribution_major_version == "12"

