- name: Add pi user to docker
  ansible.builtin.user:
    name: pi
    groups: docker
    append: true

# create different user & add user to NOPASSWORD sudo

# - name: Make sure we have a 'wheel' group
#  group:
#    name: wheel
#    state: present
#
# - name: Allow 'wheel' group to have passwordless sudo
#  lineinfile:
#    dest: /etc/sudoers
#    state: present
#    regexp: '^%wheel'
#    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
#    validate: 'visudo -cf %s'
#
# - name: Add sudoers users to wheel group
#  ansible.builtin.user:
#    name: deploy
#    groups: wheel
#    append: yes
#    state: present
#    createhome: yes
