- name: Create my user and to sudo group
  ansible.builtin.user:
    name: "{{ user }}"
    groups: sudo
    append: true
    shell: /bin/bash

- name: Add SSH key for {{ user }}
  authorized_key:
    user: "{{ user }}"
    key: "{{ key }}"

# - name: "Kill any processes for {{ user }}"
#   shell: "pkill -KILL -U {{ unwanted_user }} 2>/dev/null"
#   register: kill_result
#   changed_when: "kill_result.rc == 0"
#   failed_when: "false"
#
# - name: remove {{ unwanted_user }} 
#   ansible.builtin.user:
#     name: "{{ unwanted_user }}"
#     state: absent
- name: Add user to passwordless sudo
  copy:
    content: "oli ALL=(ALL:ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/{{ user }}"
    owner: root
    group: root
    mode: 0444
    validate: "visudo -cf %s"
