---
#Run with ansible-playbook -i inventory main.yml
- name: Setup Docker pi
  hosts: pi
  remote_user: pi
  become: true
  become_method: sudo
  gather_facts: true
  vars_files:
    - ./vars/vars.yml

  pre_tasks:
    - name: Update Apt Cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
  roles:
    - docker

#  tasks:
#    - include: tasks/packages.yml
#    - include: tasks/docker.yml
#    - include: tasks/environment.yml
#    - include: tasks/user.yml

#    - name: reboot 
#      ansible.builtin.reboot:

- name: setup nfs-server
  hosts: nfs-server
  remote_user: pi
  become: true
  become_method: sudo
  gather_facts: true
  vars_files:
    - ./vars/vars.yml
  roles:
    - nfs-server
#  tasks:
#    - include: tasks/nfs-server.yml

- name: setup nfs-clients
  hosts: pi, !nfs-server
  become: true
  become_method: sudo
  gather_facts: true
  vars_files:
    - ./vars/vars.yml
  roles:
    - nfs-client

#  tasks:
#    - include: tasks/nfs-client.yml

#    - name: reboot 
#      ansible.builtin.reboot: