---
- name: Pi Hole
  hosts: pihole
  become: true
  vars_files:
    - ./host_vars/pihole.yml

  tasks:
    - name: Check directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
      loop:
        - "{{ dnsmasq_config_dir }}"
        - "{{ pihole_config_dir }}"

    - name: Write setupVars file
      ansible.builtin.template:
        src: ../template/pihole-setupVars.conf.j2
        dest: "{{ pihole_config_dir }}/setupVars.conf"
        owner: root
        group: root

    - name: Write custom dns file
      ansible.builtin.template:
        src: ../template/custom.list.j2
        dest: "{{ pihole_config_dir }}/custom.list"
        owner: root
        group: root

    - name: Write dhcp config
      ansible.builtin.template:
        src: ../template/02-pihole-dhcp.conf.j2
        dest: "{{ pihole_config_dir }}/setupVars.conf"
        owner: root
        group: root

---
- name: Pi Hole2
  hosts: pihole2
  become: true
  vars_files:
    - ./host_vars/pihole2.yml

  tasks:
    - name: Check directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
      loop:
        - "{{ dnsmasq_config_dir }}"
        - "{{ pihole_config_dir }}"

    - name: Write setupVars file
      ansible.builtin.template:
        src: ../template/pihole-setupVars.conf.j2
        dest: "{{ pihole_config_dir }}/setupVars.conf"
        owner: root
        group: root

    - name: Write custom dns file
      ansible.builtin.template:
        src: ../template/custom.list.j2
        dest: "{{ pihole_config_dir }}/custom.list"
        owner: root
        group: root

    - name: Write dhcp config
      ansible.builtin.template:
        src: ../template/02-pihole-dhcp.conf.j2
        dest: "{{ pihole_config_dir }}/setupVars.conf"
        owner: root
        group: root
